### ISSUE TITLE
How to use it with MeshPhysicalMaterial() ?

### ISSUE THREAD

**Issue by Achuttarsing** [DerSchmale/threejs-thin-film-iridescence#3]
I know it's a basic question but .. how to use it with MeshPhysicalMaterial()?

I can't figure it out

Thank you for your help

**Comment by DerSchmale** [comment]
It's a custom material, it doesn't work with `MeshPhysicalMaterial`. However, threejs has since implemented their own iridescence support for `MeshPhysicalMaterial`, so I suppose this repo has become obsolete 😅

**Comment by DerSchmale** [comment]
Closing in favour of ThreeJS' native iridescence support.
